; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_shatterhand=music_data_shatterhand
.endif

music_data_shatterhand:
	.byte 1
	.word @music_data_shatterhand_instruments
	.word @music_data_shatterhand_samples-4
	.word @music_data_shatterhand_song0ch0,@music_data_shatterhand_song0ch1,@music_data_shatterhand_song0ch2,@music_data_shatterhand_song0ch3,@music_data_shatterhand_song0ch4 ; 00 : Final Area
	.byte .lobyte(@music_data_shatterhand_tempo_env_1_mid), .hibyte(@music_data_shatterhand_tempo_env_1_mid), 0, 0

.export music_data_shatterhand
.global FAMISTUDIO_DPCM_PTR

@music_data_shatterhand_instruments:
	.word @music_data_shatterhand_env3,@music_data_shatterhand_env6,@music_data_shatterhand_env9,@music_data_shatterhand_env0 ; 00 : Bass
	.word @music_data_shatterhand_env5,@music_data_shatterhand_env1,@music_data_shatterhand_env9,@music_data_shatterhand_env0 ; 01 : BassDrum
	.word @music_data_shatterhand_env10,@music_data_shatterhand_env8,@music_data_shatterhand_env9,@music_data_shatterhand_env0 ; 02 : CymbalHigh
	.word @music_data_shatterhand_env14,@music_data_shatterhand_env7,@music_data_shatterhand_env9,@music_data_shatterhand_env0 ; 03 : CymbalLow
	.word @music_data_shatterhand_env2,@music_data_shatterhand_env6,@music_data_shatterhand_env9,@music_data_shatterhand_env4 ; 04 : Lead-Duty0
	.word @music_data_shatterhand_env2,@music_data_shatterhand_env6,@music_data_shatterhand_env12,@music_data_shatterhand_env4 ; 05 : Lead-Duty1
	.word @music_data_shatterhand_env2,@music_data_shatterhand_env6,@music_data_shatterhand_env11,@music_data_shatterhand_env4 ; 06 : Lead-Duty2
	.word @music_data_shatterhand_env13,@music_data_shatterhand_env8,@music_data_shatterhand_env9,@music_data_shatterhand_env0 ; 07 : Snare

@music_data_shatterhand_env0:
	.byte $00,$c0,$7f,$00,$02
@music_data_shatterhand_env1:
	.byte $c0,$bf,$c1,$00,$02
@music_data_shatterhand_env2:
	.byte $06,$c8,$c9,$c5,$00,$03,$c4,$c4,$c2,$00,$08
@music_data_shatterhand_env3:
	.byte $00,$cf,$7f,$00,$02
@music_data_shatterhand_env4:
	.byte $00,$c0,$08,$c0,$04,$bd,$03,$bd,$00,$03
@music_data_shatterhand_env5:
	.byte $00,$cf,$ca,$c3,$c2,$c0,$00,$05
@music_data_shatterhand_env6:
	.byte $c0,$7f,$00,$01
@music_data_shatterhand_env7:
	.byte $c0,$c2,$c5,$00,$02
@music_data_shatterhand_env8:
	.byte $c0,$c1,$c2,$00,$02
@music_data_shatterhand_env9:
	.byte $7f,$00,$00
@music_data_shatterhand_env10:
	.byte $00,$cb,$ca,$09,$c9,$00,$04
@music_data_shatterhand_env11:
	.byte $c2,$7f,$00,$00
@music_data_shatterhand_env12:
	.byte $c1,$7f,$00,$00
@music_data_shatterhand_env13:
	.byte $00,$ca,$c6,$c3,$c0,$00,$04
@music_data_shatterhand_env14:
	.byte $00,$cb,$cb,$c5,$03,$c4,$03,$c3,$03,$c2,$00,$09

@music_data_shatterhand_samples:

@music_data_shatterhand_tempo_env_1_mid:
	.byte $03,$05,$80

@music_data_shatterhand_song0ch0:
@music_data_shatterhand_song0ch0loop:
	.byte $46, .lobyte(@music_data_shatterhand_tempo_env_1_mid), .hibyte(@music_data_shatterhand_tempo_env_1_mid), $7e, $88
@music_data_shatterhand_song0ref7:
	.byte $16, $9b, $44, $83, $19, $89, $44, $81, $43, $16, $16, $9b, $44, $83, $1b, $89, $44, $81, $43, $16, $16, $9b, $44, $83
	.byte $1e, $89, $44, $81, $43, $16, $16, $9b, $44, $83, $1d, $9b, $44, $83, $1b, $89, $44, $81, $43, $1d
@music_data_shatterhand_song0ref51:
	.byte $19, $89, $44, $81, $43, $1b, $14, $89, $44, $81, $43, $19, $47
	.byte $41, $32
	.word @music_data_shatterhand_song0ref7
	.byte $47, $00, $43, $19, $8d, $27, $89, $44, $81, $43, $14
@music_data_shatterhand_song0ref78:
	.byte $25, $89, $44, $81, $43, $27, $20, $89, $44, $81, $43, $25, $27, $89, $44, $81, $43, $20
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref78
	.byte $1b, $89, $44, $81, $43, $20
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref51
	.byte $1d, $89, $44, $81, $43, $14, $19, $89, $44, $81, $43, $1d, $14, $89, $44, $81, $43, $19, $11, $89, $44, $81, $43, $14
@music_data_shatterhand_song0ref132:
	.byte $14, $89, $44, $81, $43, $11, $16, $89, $44, $81, $43, $14, $47, $27, $89, $44, $81, $43, $16, $00, $43, $16, $8d, $1e
	.byte $89, $44, $81, $43, $27, $00, $43, $27
@music_data_shatterhand_song0ref164:
	.byte $8d, $43, $1e, $8f, $20, $89, $44, $81, $43, $1e, $00, $43, $1e, $8d, $43, $20, $8f, $1d, $89, $44, $81, $43, $20, $00
	.byte $43, $20, $8d, $43, $1d, $8f, $1e, $89, $44, $81, $43, $1d, $00, $43, $1d, $8d, $1b, $ad, $44, $83, $47, $1d, $89, $44
	.byte $81, $43, $1b, $00, $43, $1b, $8d, $19, $89, $44, $81, $43, $1d, $1b, $d1, $44, $83, $00, $43, $1b, $8d, $11, $89, $44
	.byte $81, $43, $1b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref132
	.byte $1b, $89, $44, $81, $43, $16
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref51
@music_data_shatterhand_song0ref251:
	.byte $16, $89, $44, $81, $43, $14, $47, $00, $43, $14, $8d, $43, $16, $8f, $1e, $89, $44, $81, $43, $16, $00, $43, $16
	.byte $41, $3c
	.word @music_data_shatterhand_song0ref164
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref132
	.byte $1b, $89, $44, $81, $43, $16
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref51
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref251
	.byte $8a
@music_data_shatterhand_song0ref293:
	.byte $23, $ad, $44, $83, $25, $89, $44, $81, $43, $23
@music_data_shatterhand_song0ref303:
	.byte $27, $89, $44, $81, $43, $25, $29, $89, $44, $81, $43, $27, $2a, $9b, $44, $83
@music_data_shatterhand_song0ref319:
	.byte $2c, $89, $44, $81, $43, $2a, $2a, $89, $44, $81, $43, $2c, $00, $43, $2c, $8d, $26, $ad, $44, $83, $47, $23, $bf, $44
	.byte $83, $29, $8f, $44, $81, $43, $23, $27, $8f, $44, $81, $43, $29, $26, $8f, $44, $81, $43, $27, $27, $9b, $44, $83, $22
	.byte $89, $44, $81, $43, $27, $2a, $9b, $44, $83
@music_data_shatterhand_song0ref376:
	.byte $29, $89
@music_data_shatterhand_song0ref378:
	.byte $44, $81, $43, $2a, $27, $89, $44, $81, $43, $29, $25, $89, $44, $81, $43, $27, $47, $00, $43, $27, $8d, $43, $25, $8f
	.byte $41, $13
	.word @music_data_shatterhand_song0ref293
	.byte $25, $9b, $44, $83
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref303
	.byte $00, $43, $27, $8d, $2a, $ad, $44, $83, $47, $2c, $bf
@music_data_shatterhand_song0ref423:
	.byte $44, $83, $2c, $89, $44, $83, $2e, $89, $44, $81, $43, $2c, $31, $89, $44, $81, $43, $2e, $2c, $89, $44, $81, $43, $31
	.byte $00, $43, $31, $8d, $88, $1e, $89, $44, $81, $43, $2c
@music_data_shatterhand_song0ref458:
	.byte $1d, $89, $44, $81, $43, $1e, $19, $89, $44, $81, $43, $1d, $12, $89, $44, $81, $43, $19, $11, $89, $44, $81, $43, $12
	.byte $41, $55
	.word @music_data_shatterhand_song0ref132
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref132
	.byte $1b, $89, $44, $81, $43, $16
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref51
	.byte $41, $11
	.word @music_data_shatterhand_song0ref251
	.byte $41, $3c
	.word @music_data_shatterhand_song0ref164
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref132
	.byte $1b, $89, $44, $81, $43, $16
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref51
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref251
	.byte $25, $9b, $44, $83, $25, $89, $44, $83
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref303
	.byte $29, $ad, $44, $83, $29, $89, $44, $83, $27, $89, $44, $81, $43, $29, $00, $43, $29, $8d, $26, $ad, $44, $83, $47, $27
	.byte $bf, $44, $83, $27, $89
@music_data_shatterhand_song0ref558:
	.byte $44, $83, $29, $89, $44, $81, $43, $27, $2a, $89, $44, $81, $43, $29, $2c, $ad, $44, $83, $2a, $89, $44, $81, $43, $2c
	.byte $29, $89, $44, $81, $43, $2a, $00, $43, $2a, $8d, $27, $ad, $44, $83, $47, $00, $43, $27, $9f
@music_data_shatterhand_song0ref601:
	.byte $29, $9b, $44, $83, $29, $89, $44, $83, $2a, $89, $44, $81, $43, $29, $2c, $89, $44, $81, $43, $2a, $2e, $ad, $44, $83
	.byte $2c, $89, $44, $81, $43, $2e, $2a, $89, $44, $81, $43, $2c, $00, $43, $2c, $8d
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref319
	.byte $29, $89, $44, $81, $43, $2a, $47, $26, $bf, $44, $83, $27, $bf, $44, $83, $29, $89, $44, $81, $43, $27, $29, $8b, $44
	.byte $81, $00, $43, $29, $8d, $29, $d1, $44, $83, $47, $2e, $89, $44, $81, $43, $29
@music_data_shatterhand_song0ref684:
	.byte $27, $89, $44, $81, $43, $2e, $22, $89, $44, $81, $43, $27, $2c, $89, $44, $81, $43, $22, $25, $89, $44, $81, $43, $2c
	.byte $20, $89, $44, $81, $43, $25, $1e, $9b, $44, $83, $00, $43, $1e, $8d, $1e, $89, $44, $83
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $1e, $89, $44, $81, $43, $19
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
@music_data_shatterhand_song0ref738:
	.byte $1b, $89, $44, $81, $43, $19, $47, $1e, $89, $44, $81, $43, $1b, $1e, $89, $44, $83, $00, $43, $1e, $8d, $20, $89, $44
	.byte $81, $43, $1e, $20, $89, $44, $83, $00, $43, $20, $8d, $1e, $89, $44, $81, $43, $20, $1e, $89, $44, $83, $00, $43, $1e
	.byte $8d, $20, $89, $20, $81, $43, $1e, $20, $89, $44, $83, $00, $43, $20, $8d, $27, $89, $44, $81, $43, $20, $25, $89, $44
	.byte $81, $43, $27, $23, $89, $44, $81, $43, $25, $22, $89, $44, $81, $43, $23, $47, $2e, $89, $44, $81, $43, $22
	.byte $41, $24
	.word @music_data_shatterhand_song0ref684
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $1e, $89, $44, $81, $43, $19
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $41, $49
	.word @music_data_shatterhand_song0ref738
	.byte $47, $17, $9b, $44, $83, $1e, $89, $44, $81, $43, $17, $19, $9b, $44, $83, $20, $9b, $44, $83, $1b, $9b, $44, $83, $22
	.byte $9b, $44, $83, $29, $89, $44, $81, $43, $22, $2a, $89, $44, $81, $29, $8b
	.byte $41, $0d
	.word @music_data_shatterhand_song0ref378
	.byte $47, $2a, $89, $44, $81, $43, $25, $2a, $89, $44, $83, $00, $43, $2a, $8d, $29, $89, $44, $81, $43, $2a
@music_data_shatterhand_song0ref913:
	.byte $29, $89, $44, $83, $00, $43, $29, $8d, $2a, $89, $44, $81, $43, $29, $2a, $89, $44, $83, $00, $43, $2a, $8d, $11, $89
	.byte $44, $81, $43, $2a, $16, $89, $44, $81, $43, $11, $1d, $89, $44, $81, $43, $16, $25, $89, $44, $81, $43, $1d, $29, $ad
	.byte $44, $83, $42
	.word @music_data_shatterhand_song0ch0loop
@music_data_shatterhand_song0ch1:
@music_data_shatterhand_song0ch1loop:
	.byte $8a
@music_data_shatterhand_song0ref968:
	.byte $1b, $9b, $44, $83, $1e, $89, $44, $81, $43, $1b, $1b, $9b, $44, $83, $20, $89, $44, $81, $43, $1b, $1b, $9b, $44, $83
	.byte $22, $89, $44, $81, $43, $1b, $1b, $9b, $44, $83, $20, $9b, $44, $83, $1e, $89, $44, $81, $43, $20
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $41, $28
	.word @music_data_shatterhand_song0ref968
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $00, $43, $1d, $8d, $2a, $89, $44, $81, $43, $19
@music_data_shatterhand_song0ref1031:
	.byte $29, $89, $44, $81, $43, $2a, $25, $89, $44, $81, $43, $29, $2a, $89, $44, $81, $43, $25
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1031
	.byte $1e, $89, $44, $81, $43, $25
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $20, $89, $44, $81, $43, $19, $1d, $89, $44, $81, $43, $20, $19, $89, $44, $81, $43, $1d, $16, $89, $44, $81, $43, $19
@music_data_shatterhand_song0ref1085:
	.byte $19, $89, $44, $81, $43, $16
@music_data_shatterhand_song0ref1091:
	.byte $1b, $89, $44, $81, $43, $19, $33, $89, $44, $81, $43, $1b, $00, $43, $1b, $8d, $22, $89, $44, $81, $43, $33, $00, $43
	.byte $33
@music_data_shatterhand_song0ref1116:
	.byte $8d, $43, $22, $8f, $23, $89, $44, $81, $43, $22, $00, $43, $22, $8d, $43, $23, $8f, $20, $89, $44, $81, $43, $23, $00
	.byte $43, $23, $8d, $43, $20, $8f, $22, $89, $44, $81, $43, $20, $00, $43, $20, $8d, $1e, $ad, $44, $83, $20, $89, $44, $81
	.byte $43, $1e, $00, $43, $1e, $8d, $1d, $89, $44, $81, $43, $20, $1e, $d1, $44, $83, $00, $43, $1e, $8d, $16, $89, $44, $81
	.byte $43, $1e
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1085
	.byte $1e, $89, $44, $81, $43, $1b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
@music_data_shatterhand_song0ref1202:
	.byte $1b, $89, $44, $81, $43, $19, $00, $43, $19, $8d, $43, $1b, $8f, $22, $89, $44, $81, $43, $1b, $00, $43, $1b
	.byte $41, $3c
	.word @music_data_shatterhand_song0ref1116
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1085
	.byte $1e, $89, $44, $81, $43, $1b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1202
	.byte $8c, $27, $ad
	.byte $41, $0d
	.word @music_data_shatterhand_song0ref558
@music_data_shatterhand_song0ref1248:
	.byte $89, $44, $81, $43, $2a, $2e, $9b, $44, $83
@music_data_shatterhand_song0ref1257:
	.byte $2f, $89, $44, $81, $43, $2e, $2e, $89, $44, $81, $43, $2f, $00, $43, $2f, $8d, $29, $ad, $44, $83, $2c, $bf, $44, $83
	.byte $2c, $8f, $44, $83, $2a, $8f, $44, $81, $43, $2c, $29, $8f, $44, $81, $43, $2a, $2a, $9b, $44, $83, $27, $89, $44, $81
	.byte $43, $2a, $2e, $d1, $44, $83, $00, $43, $2e, $9f, $27, $ad
	.byte $41, $0d
	.word @music_data_shatterhand_song0ref558
	.byte $41, $0d
	.word @music_data_shatterhand_song0ref1248
	.byte $31, $89, $44, $81, $43, $2f, $00, $43, $2f, $8d, $33, $ad, $44, $83, $35, $bf, $44, $83, $35, $89, $44, $83, $36, $89
	.byte $44, $81, $43, $35, $38, $89, $44, $81, $43, $36, $35, $89, $44, $81, $43, $38, $00, $43, $38, $8d, $8a, $2a, $89, $44
	.byte $81, $43, $35
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1031
	.byte $1e, $89, $44, $81, $43, $25
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $41, $50
	.word @music_data_shatterhand_song0ref1091
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1085
	.byte $1e, $89, $44, $81, $43, $1b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $41, $11
	.word @music_data_shatterhand_song0ref1202
	.byte $41, $3c
	.word @music_data_shatterhand_song0ref1116
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1085
	.byte $1e, $89, $44, $81, $43, $1b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref458
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1202
	.byte $41, $23
	.word @music_data_shatterhand_song0ref601
	.byte $29, $ad, $44, $83, $2a, $bf, $44, $83, $2a, $8b, $44, $81, $2c, $89, $44, $81, $43, $2a, $2e, $89, $44, $81, $43, $2c
	.byte $2f, $ad, $44, $83, $2e, $89, $44, $81, $43, $2f, $2c, $89, $44, $81, $43, $2e, $00, $43, $2e, $8d, $2a, $ad, $44, $83
	.byte $00, $43, $2a, $9f, $2c, $9b
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref423
	.byte $2f, $89, $44, $81, $43, $2e, $31, $ad, $44, $83, $2f, $89, $44, $81, $43, $31, $2e, $89, $44, $81, $43, $2f, $00, $43
	.byte $2f, $8d
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1257
	.byte $2c, $89, $44, $81, $43, $2e, $2e, $bf, $44, $83, $30, $bf, $44, $83, $31, $89, $44, $81, $43, $30, $31, $89, $44, $83
	.byte $00, $43, $31, $8d, $32, $d1, $44, $83, $33, $89, $44, $81, $43, $32
@music_data_shatterhand_song0ref1549:
	.byte $2e, $89, $44, $81, $43, $33, $27, $89, $44, $81, $43, $2e, $31, $89, $44, $81, $43, $27, $2c, $89, $44, $81, $43, $31
	.byte $25, $89, $44, $81, $43, $2c, $23, $9b, $44, $83, $00, $43, $23, $8d, $2a, $89, $44, $81, $43, $23
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref1031
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1031
@music_data_shatterhand_song0ref1599:
	.byte $27, $89, $44, $81, $43, $25, $23, $89, $44, $81, $43, $27, $23, $89, $44, $83, $00, $43, $23, $8d, $25, $89, $44, $81
	.byte $43, $23, $25, $89, $44, $83, $00, $43, $25, $8d, $27, $89, $44, $81, $43, $25, $27, $89, $44, $83, $00, $43, $27, $8d
	.byte $29, $89, $44, $81, $43, $27
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref913
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref376
	.byte $33, $89, $44, $81, $43, $25
	.byte $41, $25
	.word @music_data_shatterhand_song0ref1549
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref1031
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1031
	.byte $41, $2e
	.word @music_data_shatterhand_song0ref1599
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref913
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref376
	.byte $23, $9b, $44, $83, $2a, $89, $44, $81, $43, $23, $25, $9b, $44, $83, $2c, $9b, $44, $83, $27, $9b, $44, $83, $2e, $9b
	.byte $44, $83, $35, $89, $44, $81, $43, $2e, $36, $89, $44, $81, $43, $35, $35, $89, $44, $81, $43, $36, $33, $89, $44, $81
	.byte $43, $35, $31, $89, $44, $81, $43, $33
@music_data_shatterhand_song0ref1739:
	.byte $33, $89, $44, $81, $43, $31, $33, $89, $44, $83, $00, $43, $33, $8d, $31, $89, $44, $81, $43, $33, $31, $89, $44, $83
	.byte $00, $43, $31, $8d
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1739
	.byte $16, $89, $44, $81, $43, $33, $1d, $89, $44, $81, $43, $16, $22, $89, $44, $81, $43, $1d, $29, $89, $44, $81, $43, $22
	.byte $2e, $ad, $44, $83, $42
	.word @music_data_shatterhand_song0ch1loop
@music_data_shatterhand_song0ch2:
@music_data_shatterhand_song0ch2loop:
	.byte $80
@music_data_shatterhand_song0ref1803:
	.byte $1b
@music_data_shatterhand_song0ref1804:
	.byte $8b
@music_data_shatterhand_song0ref1805:
	.byte $00, $81, $1b, $8b, $00, $81, $1b, $8b, $00, $81
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $1b, $8b, $00, $81, $1b, $8b, $00, $81
@music_data_shatterhand_song0ref1829:
	.byte $19, $9d
@music_data_shatterhand_song0ref1831:
	.byte $00, $81, $16, $8b, $00, $81, $19, $8b, $00, $81, $1d
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1804
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0d
	.word @music_data_shatterhand_song0ref1829
	.byte $8b, $00, $81, $19, $f7, $00, $81, $19, $d3, $00, $81, $19, $8b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1831
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $1b, $8b, $00, $81, $1b, $8b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1831
@music_data_shatterhand_song0ref1906:
	.byte $1b, $8b, $00, $81
@music_data_shatterhand_song0ref1910:
	.byte $1e
@music_data_shatterhand_song0ref1911:
	.byte $8b, $00, $81, $1d
@music_data_shatterhand_song0ref1915:
	.byte $8b, $00, $81, $19, $8b, $00, $81, $1b
@music_data_shatterhand_song0ref1923:
	.byte $8b, $00, $81, $17, $8b, $00, $81, $17, $8b, $00, $81, $17
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $8b, $00, $81, $17, $8b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1831
	.byte $41, $14
	.word @music_data_shatterhand_song0ref1906
@music_data_shatterhand_song0ref1967:
	.byte $14, $8b, $00, $81, $14, $8b, $00, $81, $1b, $8b, $00, $81, $1e, $8b, $00, $81
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1967
@music_data_shatterhand_song0ref1986:
	.byte $16
@music_data_shatterhand_song0ref1987:
	.byte $8b, $00, $81, $16, $8b, $00, $81, $1d, $8b, $00, $81, $20, $8b, $00, $81
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1986
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1967
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1986
@music_data_shatterhand_song0ref2011:
	.byte $1b, $8b, $00, $81, $1b, $8b, $00, $81, $19, $8b, $00, $81, $19
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1923
	.byte $16, $8b, $00, $81, $16, $8b, $00, $81
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1967
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1967
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1986
	.byte $41, $10
	.word @music_data_shatterhand_song0ref1986
	.byte $17
@music_data_shatterhand_song0ref2048:
	.byte $8b, $00, $81, $17, $8b, $00, $81, $1e, $8b, $00, $81, $23
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2048
	.byte $8b, $00, $81, $19, $8b, $00, $93, $19, $8b, $00, $81, $19, $9d, $00, $81, $19, $8b, $00, $81, $19, $9d
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1805
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $16
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1915
	.byte $41, $19
	.word @music_data_shatterhand_song0ref1910
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $8b, $00, $81, $17, $8b
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref1831
	.byte $41, $14
	.word @music_data_shatterhand_song0ref1906
@music_data_shatterhand_song0ref2150:
	.byte $19
@music_data_shatterhand_song0ref2151:
	.byte $8b, $00, $81, $19, $8b, $00, $81, $19, $8b, $00, $81
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2150
	.byte $19, $8b, $00, $81, $19
@music_data_shatterhand_song0ref2170:
	.byte $8b, $00, $81, $1a, $8b, $00, $81, $1a, $8b, $00, $81, $1a
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2170
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref2170
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1803
	.byte $1b, $8b, $00, $81, $1b
@music_data_shatterhand_song0ref2199:
	.byte $8b, $00, $81, $1c, $8b, $00, $81, $1c, $8b, $00, $81, $1c
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2199
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref2199
@music_data_shatterhand_song0ref2217:
	.byte $1d, $8b, $00, $81, $1d, $8b, $00, $81, $1d, $8b, $00, $81
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2217
	.byte $1d
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1911
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2150
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2150
	.byte $19
@music_data_shatterhand_song0ref2243:
	.byte $8b, $00, $81, $16, $8b, $00, $81, $16, $8b, $00, $81, $16
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2243
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2243
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1987
	.byte $22, $9d, $00, $81, $22, $8b, $00, $81, $1d, $8b, $00, $81, $16
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1804
	.byte $1b
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref2151
@music_data_shatterhand_song0ref2284:
	.byte $19, $8b, $00, $81, $17, $af, $00, $81, $17, $8b, $00, $81, $17, $9d, $00, $81, $17, $8b, $00, $81, $17, $9d, $00, $81
	.byte $17
@music_data_shatterhand_song0ref2309:
	.byte $8b, $00, $81, $14, $8b, $00, $81, $14, $8b, $00, $81, $14
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2243
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref2151
	.byte $19
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1923
	.byte $19
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1915
	.byte $41, $0d
	.word @music_data_shatterhand_song0ref2011
	.byte $8b, $00, $81
	.byte $41, $25
	.word @music_data_shatterhand_song0ref2284
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2243
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref2151
	.byte $19
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1923
	.byte $19, $8b, $00, $81, $19
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2309
	.byte $8b, $00, $81, $14
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2243
	.byte $8b, $00, $81, $16
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref1923
	.byte $8b, $00, $81, $17
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref2151
	.byte $19
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref1915
	.byte $1b, $8b, $00, $93, $19, $8b, $00, $81, $19, $8b, $00, $93, $1b, $8b, $00, $81, $1b, $8b, $00, $93, $16
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2243
	.byte $8b, $00, $81, $16, $8b, $00, $81, $18, $8b, $00, $81, $1a, $8b, $00, $81, $42
	.word @music_data_shatterhand_song0ch2loop
@music_data_shatterhand_song0ch3:
@music_data_shatterhand_song0ch3loop:
@music_data_shatterhand_song0ref2436:
	.byte $84, $21, $a1, $86
@music_data_shatterhand_song0ref2440:
	.byte $1b, $a1, $84, $21, $a1, $86, $1b, $a1, $84, $21, $a1, $86, $1b, $a1
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2436
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref2436
	.byte $21, $a1, $21, $a1, $21, $a1, $21, $a1, $21, $a1, $86, $1b, $8f, $84, $21, $8f, $86, $1b, $81, $1b, $8b, $84
@music_data_shatterhand_song0ref2482:
	.byte $21
@music_data_shatterhand_song0ref2483:
	.byte $8f, $82, $15, $8f, $8e, $21, $8f, $86, $1b, $8f, $8e, $21, $8f, $82, $15, $8f, $15, $8f, $86, $1b, $8f, $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
@music_data_shatterhand_song0ref2512:
	.byte $8e, $21, $8f, $82, $15, $8f, $86, $1b, $8f, $1b, $8f, $82, $15, $8f, $86, $1b, $8f, $1b, $8f, $82, $15, $8f, $86, $1b
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref2483
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $41, $11
	.word @music_data_shatterhand_song0ref2512
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref2483
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e, $21, $8f, $86, $1b, $8f, $82, $15, $8f
@music_data_shatterhand_song0ref2586:
	.byte $15, $8f, $86, $1b, $8f, $82, $15, $8f, $86, $1b, $8f, $1b, $8f, $1b
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref2483
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $41, $11
	.word @music_data_shatterhand_song0ref2512
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref2483
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $41, $11
	.word @music_data_shatterhand_song0ref2512
	.byte $41, $0f
	.word @music_data_shatterhand_song0ref2483
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e
	.byte $41, $10
	.word @music_data_shatterhand_song0ref2482
	.byte $8e, $21, $8f, $86, $1b, $8f, $1b, $8f, $82
	.byte $41, $0b
	.word @music_data_shatterhand_song0ref2586
	.byte $8f, $1b, $8f
@music_data_shatterhand_song0ref2670:
	.byte $1b, $a1, $1b, $8f, $1b, $a1, $1b, $8f, $1b, $a1, $82, $15, $8f, $86, $1b, $8f, $82
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref2586
@music_data_shatterhand_song0ref2690:
	.byte $82, $15, $8f, $15, $8f, $84, $21, $8f, $82, $15, $8f, $15, $8f, $84, $21, $8f
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2690
	.byte $86, $1b, $a1
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref2670
	.byte $1b, $8f, $1b, $a1, $82, $15, $8f, $86, $1b, $8f, $82
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref2586
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2690
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2690
	.byte $86, $1b, $a1
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref2440
	.byte $84, $21, $a1, $86, $1b, $a1, $84, $21, $a1, $86
	.byte $41, $0a
	.word @music_data_shatterhand_song0ref2670
	.byte $1b, $8f, $1b, $a1, $1b, $8f, $1b, $8f, $1b, $8f, $1b, $8f, $1b, $8f, $82, $15, $8f, $15, $8f, $42
	.word @music_data_shatterhand_song0ch3loop
@music_data_shatterhand_song0ch4:
@music_data_shatterhand_song0ch4loop:
@music_data_shatterhand_song0ref2777:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2777
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2777
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2777
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2777
	.byte $41, $0c
	.word @music_data_shatterhand_song0ref2777
	.byte $ff, $ff, $9f, $42
	.word @music_data_shatterhand_song0ch4loop
